name: ci
on: push

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deno
            - run: |
                deno task build online
                npm install -g gh-pages --save-dev
                cd release
                gh-pages -d online --nojekyll


